services:
  accounts:
    image: "habibiayoub/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - habibiayoub
  loans:
    image: "habibiayoub/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - habibiayoub
  cards:
    image: "habibiayoub/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - habibiayoub
networks:
  habibiayoub:
    driver: "bridge"