spring:
  application:
    name: "message"
  cloud:
    function:
      definition: email|sms
    stream:
      bindings:
        email|sms-in-0:
          destination: send-communication
          group: ${spring.application.name}
        email|sms-out-0:
          destination: communication-sent
      kafka:
        binder:
          brokers:
            - localhost:9092
      default-binder: kafka
  #rabbitmq:
  #  host: localhost
  #  port: 5672
  #  username: guest
  #  password: guest
  #  connection-timeout: 10s

server:
  port: 9010
